import { sequelize } from "../src/db"

const organization = [
	{name: "Netherlands"},
	{name: "South Africa"},
	{name: "Spain"},
	{name: "United States"},
	{name: "Sweden"},
	{name: "Germany"},
	{name: "France"},
	{name: "Singapore"},
	{name: "Argentina"},
	{name: "Costa Rica"}
]

const locations = [
{name:"Biito",address:"80284 Calypso Circle",cityId:2},
{name:"Al Jīzah",address:"37970 Arizona Plaza",cityId:4},
{name:"Cipari",address:"32263 Vernon Plaza",cityId:2},
{name:"Dolsk",address:"151 Barby Trail",cityId:5},
{name:"Vicente Guerrero",address:"06 8th Pass",cityId:5},
{name:"Huangnaihai",address:"2 Moose Alley",cityId:2},
{name:"Vaiamonte",address:"11485 Coleman Avenue",cityId:4},
{name:"Libmanan",address:"2130 Norway Maple Center",cityId:2},
{name:"Huddinge",address:"7 Sugar Crossing",cityId:4},
{name:"Wanju",address:"575 Pearson Crossing",cityId:2},
{name:"Bogovinje",address:"9386 Colorado Alley",cityId:1},
{name:"Tytuvėnėliai",address:"08024 Muir Avenue",cityId:5},
{name:"Guimarei",address:"1 6th Parkway",cityId:5},
{name:"Cruz das Almas",address:"22 Monument Center",cityId:3},
{name:"Al Manşūrah",address:"66 Sundown Street",cityId:5},
{name:"Longshan",address:"2555 Sloan Drive",cityId:5},
{name:"Jishi",address:"7710 Chive Point",cityId:4},
{name:"Haihui",address:"58382 Derek Court",cityId:2},
{name:"Chahe",address:"5506 Summer Ridge Way",cityId:1},
{name:"Nuevo Emperador",address:"4 Corben Place",cityId:2}
]

let events =[
		{name:"Smiling Lieutenant, The",description:"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",organizationId:8},
		{name:"It All Starts Today (Ça commence aujourd'hui)",description:"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",organizationId:8},
		{name:"April Fool's Day",description:"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",organizationId:7},
		{name:"Magnificent Obsession",description:"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",organizationId:1},
		{name:"My Kid Could Paint That",description:"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",organizationId:5},
		{name:"Return to Never Land",description:"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",organizationId:7},
		{name:"Isadora",description:"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",organizationId:2},
		{name:"Pursuit of Happyness, The",description:"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",organizationId:4},
		{name:"Black Magic Rites & the Secret Orgies of the 14th Century (Riti, magie nere e segrete orge nel trecento...)",description:"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",organizationId:3},
		{name:"Seas Beneath",description:"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",organizationId:2},
		{name:"Contraband",description:"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",organizationId:3},
		{name:"Inside Paris (Dans Paris)",description:"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",organizationId:1},
		{name:"Show of Force, A",description:"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",organizationId:4},
		{name:"Don",description:"Phasellus in felis. Donec semper sapien a libero. Nam dui.",organizationId:4},
		{name:"Hypnotist, The (Hypnotisören)",description:"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",organizationId:5},
		{name:"Next Door (Naboer)",description:"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",organizationId:6},
		{name:"Glee: The 3D Concert Movie",description:"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",organizationId:5},
		{name:"Jack Frost",description:"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",organizationId:8},
		{name:"Ghost Story",description:"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",organizationId:5},
		{name:"The Gang That Sold America",description:"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",organizationId:6},
		{name:"Together Again",description:"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",organizationId:6},
		{name:"Never Make It Home",description:"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",organizationId:1},
		{name:"Adanggaman",description:"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",organizationId:1},
		{name:"29th Street",description:"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",organizationId:8},
		{name:"Scream 2",description:"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",organizationId:4},
		{name:"Higher Learning",description:"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",organizationId:7},
		{name:"Passengers",description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",organizationId:3},
		{name:"Darkman",description:"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",organizationId:3},
		{name:"Fanny and Alexander (Fanny och Alexander)",description:"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",organizationId:1},
		{name:"Snowblind",description:"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",organizationId:6},
		{name:"Victim",description:"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",organizationId:5},
		{name:"Exit Through the Gift Shop",description:"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",organizationId:7},
		{name:"Run, Man, Run! (Corri uomo corri)",description:"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",organizationId:3},
		{name:"Pekka ja Pätkä neekereinä",description:"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",organizationId:1},
		{name:"Thing from Another World, The",description:"In congue. Etiam justo. Etiam pretium iaculis justo.",organizationId:8},
		{name:"Lesser Blessed, The",description:"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",organizationId:8},
		{name:"Breakfast Club, The",description:"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",organizationId:1},
		{name:"Unfaithfully Yours",description:"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",organizationId:2},
		{name:"Spy Who Loved Me, The",description:"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",organizationId:8},
		{name:"Hatchet for the Honeymoon (Rosso segno della follia, Il)",description:"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",organizationId:10},
		{name:"Army of Shadows (L'armée des ombres)",description:"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",organizationId:10},
		{name:"For Roseanna (Roseanna's Grave)",description:"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",organizationId:7},
		{name:"Sonatine (Sonachine)",description:"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",organizationId:6},
		{name:"Gamera vs. Guiron",description:"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",organizationId:2},
		{name:"My Kidnapper",description:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",organizationId:7},
		{name:"Frankenstein Meets the Wolf Man",description:"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",organizationId:1},
		{name:"Tap",description:"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",organizationId:5},
		{name:"Chattahoochee",description:"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",organizationId:4},
		{name:"Black and White in Color (Noirs et blancs en couleur)",description:"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",organizationId:6},
		{name:"Hardcore",description:"Phasellus in felis. Donec semper sapien a libero. Nam dui.",organizationId:5},
		{name:"Older Brother, Younger Sister (Ani imôto)",description:"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",organizationId:10},
		{name:"Sunday in the Country, A (Un dimanche à la campagne)",description:"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",organizationId:4},
		{name:"Elephant Man, The",description:"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",organizationId:1},
		{name:"Long, Long Trailer, The",description:"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",organizationId:5},
		{name:"Being There",description:"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",organizationId:2},
		{name:"Singh Is Kinng",description:"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",organizationId:10},
		{name:"Tron",description:"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",organizationId:8},
		{name:"Dallas: War of the Ewings",description:"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",organizationId:4},
		{name:"The Expedition to the End of the World",description:"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",organizationId:5},
		{name:"Extraordinary Adventures of Mr. West in the Land of the Bolsheviks, The (Neobychainye priklyucheniya mistera Vesta v strane bolshevikov)",description:"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",organizationId:7},
		{name:"Inherit the Wind",description:"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",organizationId:5},
		{name:"No God, No Master",description:"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",organizationId:7},
		{name:"Scorned",description:"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",organizationId:8},
		{name:"Blossoms in the Dust",description:"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",organizationId:3},
		{name:"Philosophers, The (After The Dark)",description:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",organizationId:4},
		{name:"Company of Wolves, The",description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",organizationId:10},
		{name:"Life with Father",description:"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",organizationId:3},
		{name:"FM",description:"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",organizationId:1},
		{name:"Garden of the Finzi-Continis, The (Giardino dei Finzi-Contini, Il)",description:"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",organizationId:4},
		{name:"Martin & Orloff",description:"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",organizationId:3},
		{name:"Ladies in Lavender",description:"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",organizationId:6},
		{name:"Gay Deceivers, The",description:"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",organizationId:2},
		{name:"Life as We Know It",description:"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",organizationId:4},
		{name:"Werckmeister Harmonies (Werckmeister harmóniák)",description:"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",organizationId:5},
		{name:"Silver Streak",description:"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",organizationId:7},
		{name:"Commando",description:"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",organizationId:4},
		{name:"Solar Crisis",description:"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",organizationId:10},
		{name:"Last Train Home",description:"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",organizationId:7},
		{name:"Wilderness",description:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",organizationId:4},
		{name:"Rocket, The",description:"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",organizationId:1},
		{name:"Popular Music (Populärmusik från Vittula)",description:"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",organizationId:3},
		{name:"Diplomatic Immunity (2009– )",description:"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",organizationId:10},
		{name:"Doomsday",description:"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",organizationId:10},
		{name:"Love Is a Many-Splendored Thing",description:"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",organizationId:9},
		{name:"Brief History of Time, A",description:"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",organizationId:5},
		{name:"This Special Friendship (Les amitiés particulières)",description:"Phasellus in felis. Donec semper sapien a libero. Nam dui.",organizationId:9},
		{name:"Norman",description:"In congue. Etiam justo. Etiam pretium iaculis justo.",organizationId:7},
		{name:"Stakeout",description:"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",organizationId:10},
		{name:"Ladies in Lavender",description:"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",organizationId:2},
		{name:"Mr. Popper's Penguins",description:"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",organizationId:1},
		{name:"Ajami",description:"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",organizationId:8},
		{name:"About Face: Supermodels Then and Now",description:"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",organizationId:7},
		{name:"Angel of Mine (a.k.a. The Mark of an Angel) (L'empreinte de l'ange)",description:"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",organizationId:8},
		{name:"Juche Idea, The",description:"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",organizationId:5},
		{name:"Scarecrows",description:"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",organizationId:9},
		{name:"Plans for Tomorrow (Planes para mañana)",description:"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",organizationId:2},
		{name:"Ring Finger, The (L'annulaire)",description:"Phasellus in felis. Donec semper sapien a libero. Nam dui.",organizationId:6},
		{name:"Mo' Money",description:"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",organizationId:10},
		{name:"Devils on the Doorstep (Guizi lai le)",description:"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",organizationId:4},
		{name:"Perfect Murder, A",description:"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",organizationId:6}
]

const eventLocations = [
{eventId:1,locationId:6},
{eventId:2,locationId:10},
{eventId:3,locationId:7},
{eventId:4,locationId:1},
{eventId:5,locationId:14},
{eventId:6,locationId:18},
{eventId:7,locationId:19},
{eventId:8,locationId:11},
{eventId:9,locationId:3},
{eventId:10,locationId:17},
{eventId:11,locationId:13},
{eventId:12,locationId:14},
{eventId:13,locationId:16},
{eventId:14,locationId:8},
{eventId:15,locationId:4},
{eventId:16,locationId:8},
{eventId:17,locationId:10},
{eventId:18,locationId:4},
{eventId:19,locationId:11},
{eventId:20,locationId:15},
{eventId:21,locationId:6},
{eventId:22,locationId:16},
{eventId:23,locationId:9},
{eventId:24,locationId:4},
{eventId:25,locationId:14},
{eventId:26,locationId:6},
{eventId:27,locationId:13},
{eventId:28,locationId:10},
{eventId:29,locationId:16},
{eventId:30,locationId:10},
{eventId:31,locationId:14},
{eventId:32,locationId:5},
{eventId:33,locationId:15},
{eventId:34,locationId:20},
{eventId:35,locationId:8},
{eventId:36,locationId:13},
{eventId:37,locationId:1},
{eventId:38,locationId:2},
{eventId:39,locationId:8},
{eventId:40,locationId:13},
{eventId:41,locationId:18},
{eventId:42,locationId:17},
{eventId:43,locationId:16},
{eventId:44,locationId:20},
{eventId:45,locationId:4},
{eventId:46,locationId:16},
{eventId:47,locationId:15},
{eventId:48,locationId:12},
{eventId:49,locationId:11},
{eventId:50,locationId:9},
{eventId:51,locationId:18},
{eventId:52,locationId:2},
{eventId:53,locationId:11},
{eventId:54,locationId:18},
{eventId:55,locationId:8},
{eventId:56,locationId:10},
{eventId:57,locationId:13},
{eventId:58,locationId:2},
{eventId:59,locationId:1},
{eventId:60,locationId:17},
{eventId:61,locationId:4},
{eventId:62,locationId:19},
{eventId:63,locationId:9},
{eventId:64,locationId:8},
{eventId:65,locationId:18},
{eventId:66,locationId:7},
{eventId:67,locationId:4},
{eventId:68,locationId:6},
{eventId:69,locationId:7},
{eventId:70,locationId:13},
{eventId:71,locationId:7},
{eventId:72,locationId:14},
{eventId:73,locationId:4},
{eventId:74,locationId:15},
{eventId:75,locationId:13},
{eventId:76,locationId:8},
{eventId:77,locationId:1},
{eventId:78,locationId:17},
{eventId:79,locationId:19},
{eventId:80,locationId:20},
{eventId:81,locationId:15},
{eventId:82,locationId:9},
{eventId:83,locationId:18},
{eventId:84,locationId:12},
{eventId:85,locationId:18},
{eventId:86,locationId:14},
{eventId:87,locationId:9},
{eventId:88,locationId:1},
{eventId:89,locationId:14},
{eventId:90,locationId:7},
{eventId:91,locationId:3},
{eventId:92,locationId:20},
{eventId:93,locationId:13},
{eventId:94,locationId:19},
{eventId:95,locationId:3},
{eventId:96,locationId:5},
{eventId:97,locationId:15},
{eventId:98,locationId:3},
{eventId:99,locationId:16},
{eventId:100,locationId:3},
{eventId:95,locationId:9},
{eventId:73,locationId:3},
{eventId:8,locationId:19},
{eventId:37,locationId:19},
{eventId:98,locationId:6},
{eventId:35,locationId:15},
{eventId:37,locationId:15},
{eventId:89,locationId:18},
{eventId:14,locationId:2},
{eventId:45,locationId:5},
{eventId:58,locationId:6},
{eventId:50,locationId:4},
{eventId:75,locationId:20},
{eventId:44,locationId:19},
{eventId:76,locationId:2},
{eventId:22,locationId:5},
{eventId:14,locationId:1},
{eventId:4,locationId:17},
{eventId:8,locationId:10},
{eventId:74,locationId:5}
]

const dates = [
{date:"16/5/2024",price:1957,eventLocationId:1},
{date:"6/9/2022",price:752,eventLocationId:2},
{date:"3/10/2021",price:1491,eventLocationId:3},
{date:"30/6/2023",price:708,eventLocationId:4},
{date:"25/5/2023",price:1619,eventLocationId:5},
{date:"15/9/2024",price:1428,eventLocationId:6},
{date:"12/2/2022",price:1048,eventLocationId:7},
{date:"19/5/2024",price:1328,eventLocationId:8},
{date:"24/11/2022",price:1551,eventLocationId:9},
{date:"4/3/2024",price:549,eventLocationId:10},
{date:"30/1/2026",price:1553,eventLocationId:11},
{date:"8/8/2022",price:962,eventLocationId:12},
{date:"7/7/2023",price:1028,eventLocationId:13},
{date:"11/2/2025",price:1778,eventLocationId:14},
{date:"21/5/2023",price:592,eventLocationId:15},
{date:"20/4/2023",price:1296,eventLocationId:16},
{date:"20/1/2025",price:1876,eventLocationId:17},
{date:"28/1/2024",price:1631,eventLocationId:18},
{date:"16/8/2024",price:1397,eventLocationId:19},
{date:"6/4/2025",price:1212,eventLocationId:20},
{date:"11/4/2022",price:1311,eventLocationId:21},
{date:"19/7/2021",price:1636,eventLocationId:22},
{date:"22/6/2021",price:907,eventLocationId:23},
{date:"27/4/2023",price:1758,eventLocationId:24},
{date:"28/10/2025",price:644,eventLocationId:25},
{date:"24/9/2021",price:1101,eventLocationId:26},
{date:"21/1/2023",price:1923,eventLocationId:27},
{date:"11/9/2023",price:983,eventLocationId:28},
{date:"16/10/2025",price:653,eventLocationId:29},
{date:"5/9/2022",price:1191,eventLocationId:30},
{date:"12/7/2025",price:634,eventLocationId:31},
{date:"1/12/2022",price:663,eventLocationId:32},
{date:"25/12/2023",price:950,eventLocationId:33},
{date:"2/6/2024",price:1958,eventLocationId:34},
{date:"30/11/2025",price:1763,eventLocationId:35},
{date:"15/11/2021",price:1643,eventLocationId:36},
{date:"24/9/2022",price:1764,eventLocationId:37},
{date:"23/11/2023",price:761,eventLocationId:38},
{date:"26/1/2025",price:1522,eventLocationId:39},
{date:"13/12/2022",price:1557,eventLocationId:40},
{date:"19/6/2025",price:1992,eventLocationId:41},
{date:"12/9/2021",price:1305,eventLocationId:42},
{date:"10/9/2023",price:1274,eventLocationId:43},
{date:"10/9/2022",price:1031,eventLocationId:44},
{date:"8/3/2025",price:515,eventLocationId:45},
{date:"10/12/2021",price:510,eventLocationId:46},
{date:"11/6/2022",price:1499,eventLocationId:47},
{date:"13/8/2022",price:1465,eventLocationId:48},
{date:"17/10/2022",price:1310,eventLocationId:49},
{date:"6/9/2023",price:545,eventLocationId:50},
{date:"29/9/2024",price:1010,eventLocationId:51},
{date:"26/2/2025",price:1440,eventLocationId:52},
{date:"23/11/2023",price:737,eventLocationId:53},
{date:"17/10/2021",price:974,eventLocationId:54},
{date:"25/6/2021",price:1759,eventLocationId:55},
{date:"1/11/2022",price:1502,eventLocationId:56},
{date:"2/11/2022",price:1942,eventLocationId:57},
{date:"1/11/2023",price:932,eventLocationId:58},
{date:"12/9/2023",price:997,eventLocationId:59},
{date:"18/9/2022",price:1191,eventLocationId:60},
{date:"11/8/2022",price:1785,eventLocationId:61},
{date:"19/7/2025",price:1850,eventLocationId:62},
{date:"15/1/2025",price:664,eventLocationId:63},
{date:"22/5/2023",price:728,eventLocationId:64},
{date:"4/2/2022",price:1452,eventLocationId:65},
{date:"19/5/2024",price:528,eventLocationId:66},
{date:"30/7/2021",price:508,eventLocationId:67},
{date:"23/2/2024",price:1017,eventLocationId:68},
{date:"4/5/2023",price:1598,eventLocationId:69},
{date:"2/10/2022",price:1852,eventLocationId:70},
{date:"30/1/2024",price:1300,eventLocationId:71},
{date:"1/3/2024",price:958,eventLocationId:72},
{date:"6/9/2025",price:1883,eventLocationId:73},
{date:"11/10/2023",price:1097,eventLocationId:74},
{date:"20/11/2025",price:709,eventLocationId:75},
{date:"3/11/2021",price:1271,eventLocationId:76},
{date:"6/7/2022",price:1587,eventLocationId:77},
{date:"7/7/2023",price:990,eventLocationId:78},
{date:"6/10/2024",price:1590,eventLocationId:79},
{date:"5/4/2025",price:1686,eventLocationId:80},
{date:"16/1/2023",price:784,eventLocationId:81},
{date:"28/3/2022",price:1070,eventLocationId:82},
{date:"22/6/2025",price:963,eventLocationId:83},
{date:"5/3/2025",price:1056,eventLocationId:84},
{date:"24/1/2022",price:1054,eventLocationId:85},
{date:"1/1/2022",price:747,eventLocationId:86},
{date:"17/1/2026",price:580,eventLocationId:87},
{date:"29/7/2021",price:1620,eventLocationId:88},
{date:"11/2/2022",price:1521,eventLocationId:89},
{date:"12/7/2022",price:1001,eventLocationId:90},
{date:"31/1/2025",price:1429,eventLocationId:91},
{date:"24/12/2021",price:728,eventLocationId:92},
{date:"21/1/2022",price:1729,eventLocationId:93},
{date:"14/3/2023",price:1467,eventLocationId:94},
{date:"8/4/2023",price:1761,eventLocationId:95},
{date:"11/11/2022",price:1114,eventLocationId:96},
{date:"16/6/2021",price:1051,eventLocationId:97},
{date:"27/6/2025",price:748,eventLocationId:98},
{date:"17/7/2024",price:1900,eventLocationId:99},
{date:"22/7/2025",price:1913,eventLocationId:100},
{date:"23/10/2021",price:1005,eventLocationId:45},
{date:"12/6/2025",price:1090,eventLocationId:11},
{date:"27/4/2022",price:1102,eventLocationId:28},
{date:"8/9/2023",price:1413,eventLocationId:76},
{date:"28/12/2022",price:1068,eventLocationId:76},
{date:"12/4/2025",price:1515,eventLocationId:66},
{date:"13/10/2025",price:582,eventLocationId:23},
{date:"29/4/2023",price:584,eventLocationId:33},
{date:"23/2/2025",price:1750,eventLocationId:87},
{date:"14/6/2024",price:1515,eventLocationId:100},
{date:"10/7/2023",price:1696,eventLocationId:63},
{date:"6/8/2022",price:786,eventLocationId:34},
{date:"19/1/2023",price:1478,eventLocationId:50},
{date:"13/3/2022",price:759,eventLocationId:76},
{date:"1/1/2023",price:743,eventLocationId:41},
{date:"16/10/2025",price:736,eventLocationId:74},
{date:"26/5/2023",price:1790,eventLocationId:63},
{date:"24/6/2022",price:1381,eventLocationId:41},
{date:"8/4/2022",price:1434,eventLocationId:49},
{date:"30/8/2023",price:635,eventLocationId:25},
{date:"6/12/2022",price:967,eventLocationId:63},
{date:"19/11/2025",price:1217,eventLocationId:11},
{date:"1/9/2021",price:1053,eventLocationId:29},
{date:"27/7/2022",price:1891,eventLocationId:55},
{date:"10/11/2025",price:618,eventLocationId:19},
{date:"31/10/2025",price:1014,eventLocationId:14},
{date:"17/8/2024",price:1193,eventLocationId:46},
{date:"27/9/2021",price:1040,eventLocationId:100},
{date:"19/4/2025",price:878,eventLocationId:35},
{date:"26/6/2021",price:1114,eventLocationId:39},
{date:"5/11/2023",price:698,eventLocationId:40},
{date:"22/6/2021",price:910,eventLocationId:91},
{date:"8/10/2022",price:1313,eventLocationId:55},
{date:"12/10/2024",price:1369,eventLocationId:6},
{date:"10/2/2023",price:1393,eventLocationId:83},
{date:"25/9/2022",price:777,eventLocationId:24},
{date:"28/1/2024",price:690,eventLocationId:84},
{date:"8/12/2023",price:1525,eventLocationId:82},
{date:"1/3/2022",price:578,eventLocationId:55},
{date:"16/7/2022",price:1714,eventLocationId:24},
{date:"21/6/2024",price:1978,eventLocationId:13},
{date:"2/1/2022",price:803,eventLocationId:10},
{date:"21/10/2024",price:1910,eventLocationId:28},
{date:"7/2/2024",price:594,eventLocationId:27},
{date:"26/2/2023",price:1497,eventLocationId:75},
{date:"23/6/2023",price:935,eventLocationId:40},
{date:"1/8/2025",price:1608,eventLocationId:22},
{date:"9/7/2024",price:1264,eventLocationId:82},
{date:"10/4/2025",price:927,eventLocationId:88},
{date:"6/8/2023",price:1125,eventLocationId:24},
{date:"3/2/2022",price:721,eventLocationId:57},
{date:"29/4/2025",price:1407,eventLocationId:39},
{date:"26/7/2023",price:1404,eventLocationId:25},
{date:"1/12/2024",price:1313,eventLocationId:92},
{date:"21/12/2023",price:1288,eventLocationId:46},
{date:"7/4/2024",price:562,eventLocationId:20},
{date:"7/9/2022",price:841,eventLocationId:38},
{date:"14/4/2025",price:1851,eventLocationId:62},
{date:"7/10/2023",price:1913,eventLocationId:59},
{date:"22/5/2022",price:504,eventLocationId:34},
{date:"16/2/2024",price:1311,eventLocationId:11},
{date:"4/1/2023",price:1961,eventLocationId:56},
{date:"8/10/2025",price:1095,eventLocationId:48},
{date:"10/3/2025",price:1461,eventLocationId:78},
{date:"3/3/2024",price:1136,eventLocationId:41},
{date:"12/12/2025",price:581,eventLocationId:67},
{date:"2/12/2025",price:1417,eventLocationId:68},
{date:"9/6/2023",price:593,eventLocationId:79},
{date:"12/3/2024",price:1321,eventLocationId:1},
{date:"28/9/2021",price:1390,eventLocationId:4},
{date:"14/1/2022",price:1228,eventLocationId:14},
{date:"18/2/2024",price:1430,eventLocationId:99},
{date:"13/7/2021",price:946,eventLocationId:31},
{date:"21/4/2025",price:723,eventLocationId:39},
{date:"25/11/2022",price:514,eventLocationId:10},
{date:"8/9/2024",price:969,eventLocationId:10},
{date:"27/12/2021",price:1222,eventLocationId:98},
{date:"11/11/2023",price:1647,eventLocationId:95},
{date:"8/11/2022",price:1000,eventLocationId:47},
{date:"18/7/2021",price:1579,eventLocationId:11},
{date:"22/6/2024",price:941,eventLocationId:55},
{date:"23/4/2025",price:1861,eventLocationId:55},
{date:"7/6/2021",price:1469,eventLocationId:93},
{date:"11/7/2023",price:871,eventLocationId:1},
{date:"17/6/2024",price:1598,eventLocationId:21},
{date:"14/2/2022",price:1600,eventLocationId:59},
{date:"26/8/2022",price:511,eventLocationId:87},
{date:"5/4/2022",price:1931,eventLocationId:100},
{date:"8/2/2024",price:1064,eventLocationId:41},
{date:"28/4/2023",price:1854,eventLocationId:17},
{date:"29/7/2023",price:868,eventLocationId:54},
{date:"26/12/2021",price:1064,eventLocationId:55},
{date:"14/9/2024",price:862,eventLocationId:93},
{date:"28/1/2024",price:753,eventLocationId:97},
{date:"17/2/2024",price:1712,eventLocationId:53},
{date:"7/5/2022",price:982,eventLocationId:85},
{date:"1/2/2023",price:1089,eventLocationId:13},
{date:"28/12/2025",price:1830,eventLocationId:91},
{date:"27/9/2025",price:693,eventLocationId:61},
{date:"10/8/2024",price:578,eventLocationId:26}
]

const categories = [
{name: "Infantil"},
{name: "Deportes"},
{name: "Musical"},
{name: "Teatro"},
{name: "Especiales"}
]

const cities = [
{name:"Chile"},
{name:"Argentina"},
{name:"Russia"},
{name:"China"},
{name:"Croatia"}
]

const images = [
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/tickete01.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/ke-personajes.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/ismael.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400_sin_logo.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400_17.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/mesa_de_trabajo_2.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/pieza-banana-ticketek-960-x-400-px.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/jc960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/2_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/sele960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/kev960_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/volar960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/imaguare-960x400.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/pat89960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/lauren960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/ciro960_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/ciro960_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400german.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/cordo960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960_5.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/pieza-ticketek-960-x-400-px.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/mau960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/maxi960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/piano-gen960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/960x4001.jpg",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/masters960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/masters960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/960x400_mbpr.jpg",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/noventosa_verano_reprogramado.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/biza960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/dust960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/rid960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/miran960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/pieza-ticketek-960-x-400-px1.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/luc960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/pier960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/park960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/angela_960x400.jpg",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400-copia_1.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400mana_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400mana_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/cafcor960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/dsjgen960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400_65.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/sugo960_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/artist/cata440.jpg",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/radagen960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/cuart960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/wall960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/dalma960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/ort960.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400-copia_1.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400mana_0.png",
	"https://static6.ticketek.com.ar/cms_static/sites/default/files/styles/artists_list_featured/public/images/show-header/960x400et.png"
]

const users = [
	{name:"Melessa",surname:"Dayborne",email:"mdayborne0@ycombinator.com",password:"GQEKOU"},
{name:"Alvan",surname:"Van Driel",email:"avandriel1@dedecms.com",password:"Zw25NF8"},
{name:"Bradford",surname:"Wressell",email:"bwressell2@discuz.net",password:"w1SpGeoM"},
{name:"Alessandro",surname:"Ide",email:"aide3@irs.gov",password:"koYA1JM9kJ"},
{name:"Penny",surname:"Chalfain",email:"pchalfain4@usatoday.com",password:"0vmKNsU7eZMt"},
{name:"Smitty",surname:"Szapiro",email:"sszapiro5@nps.gov",password:"McAwk5dM"},
{name:"Bonnee",surname:"Powles",email:"bpowles6@mit.edu",password:"RjNN0u4uU"},
{name:"Chelsae",surname:"Vanelli",email:"cvanelli7@senate.gov",password:"3QDiOVGjujd"},
{name:"Alanna",surname:"Dare",email:"adare8@home.pl",password:"8wbkyhN5LT"},
{name:"Percival",surname:"Wilkins",email:"pwilkins9@gravatar.com",password:"WUcnAgpJ"},
{name:"Dorita",surname:"Battle",email:"dbattlea@statcounter.com",password:"MHvMjJz4"},
{name:"Sharyl",surname:"Connelly",email:"sconnellyb@csmonitor.com",password:"Ub8dXaaK"},
{name:"Leif",surname:"Lere",email:"llerec@blogger.com",password:"40ueS9GgS1Ae"},
{name:"Shalom",surname:"Fairley",email:"sfairleyd@intel.com",password:"LuxVahs"},
{name:"Sid",surname:"Keogh",email:"skeoghe@mayoclinic.com",password:"7EoteZ2bSV"},
{name:"Hiram",surname:"Darwent",email:"hdarwentf@smh.com.au",password:"cCXskozAaEX"},
{name:"Leona",surname:"Dulwich",email:"ldulwichg@about.com",password:"2NwgueE13u"},
{name:"Marco",surname:"Scandrick",email:"mscandrickh@mac.com",password:"iOKl2if"},
{name:"Valentijn",surname:"Petrik",email:"vpetriki@springer.com",password:"2Vcb69Hkwum"},
{name:"Michaeline",surname:"Cawse",email:"mcawsej@google.com",password:"DozfjQSwXLJU"},
{name:"Mikaela",surname:"Barczynski",email:"mbarczynskik@squarespace.com",password:"Cdcg9nOpxua"},
{name:"Ingmar",surname:"Raun",email:"iraunl@mysql.com",password:"ArD0NLaq"},
{name:"Malanie",surname:"Arran",email:"marranm@tripod.com",password:"aL5qvmfLo"},
{name:"Andreas",surname:"Olyfant",email:"aolyfantn@xing.com",password:"0nB60U"},
{name:"Lionello",surname:"Lawford",email:"llawfordo@adobe.com",password:"ByI46CZvl9"},
{name:"George",surname:"Bramhall",email:"gbramhallp@exblog.jp",password:"eviBulYSyN"},
{name:"Gordie",surname:"Kingswood",email:"gkingswoodq@fastcompany.com",password:"bApbcqpyA0"},
{name:"Nelia",surname:"Harrington",email:"nharringtonr@wordpress.org",password:"IVuFxAK"},
{name:"Efren",surname:"Hymer",email:"ehymers@sun.com",password:"b2bpMoG0OhVU"},
{name:"Nolana",surname:"Archbould",email:"narchbouldt@bandcamp.com",password:"Wd9oYB9egg4f"},
{name:"Morly",surname:"Vaudre",email:"mvaudreu@google.co.uk",password:"tmtxAGk"},
{name:"Patten",surname:"Owlner",email:"powlnerv@netvibes.com",password:"mk25bXwRe"},
{name:"Caryl",surname:"Coite",email:"ccoitew@xrea.com",password:"S4hZ5OyQ04i"},
{name:"Moses",surname:"Batchelder",email:"mbatchelderx@ucsd.edu",password:"6XGAsSDmJJ"},
{name:"Marie-jeanne",surname:"Ashdown",email:"mashdowny@technorati.com",password:"304DvW"},
{name:"Wandie",surname:"Highway",email:"whighwayz@chronoengine.com",password:"mwTEjznWw"},
{name:"Lavinie",surname:"McAree",email:"lmcaree10@arizona.edu",password:"I08IwLh8e"},
{name:"Theresa",surname:"Muino",email:"tmuino11@tmall.com",password:"DtNE2q"},
{name:"Belia",surname:"Marvel",email:"bmarvel12@is.gd",password:"twZkjtT"},
{name:"Marybeth",surname:"Baguley",email:"mbaguley13@oakley.com",password:"WNHuEM7FF0n"},
{name:"Chicky",surname:"Gieves",email:"cgieves14@sohu.com",password:"zZpUzK9tOU6x"},
{name:"Daryle",surname:"Spaduzza",email:"dspaduzza15@facebook.com",password:"0hUYcT"},
{name:"Stephannie",surname:"Tolliday",email:"stolliday16@epa.gov",password:"cOp9iqWxA4"},
{name:"Malchy",surname:"Sultana",email:"msultana17@hibu.com",password:"uuQSny"},
{name:"Corbin",surname:"Sloey",email:"csloey18@ed.gov",password:"E75y8VCE"},
{name:"Chuck",surname:"Dingate",email:"cdingate19@yellowbook.com",password:"KVySosfUCcz9"},
{name:"Denys",surname:"Binfield",email:"dbinfield1a@themeforest.net",password:"XiixtrHRT"},
{name:"Lavinie",surname:"Woodyear",email:"lwoodyear1b@rediff.com",password:"5nS9fMNsqz"},
{name:"Federico",surname:"Olin",email:"folin1c@cargocollective.com",password:"kZAaMQUY"},
{name:"Inna",surname:"Kiddell",email:"ikiddell1d@house.gov",password:"aSbAi2wdBN"},
{name:"Hurlee",surname:"McGeaney",email:"hmcgeaney1e@google.com.au",password:"gNdkNWxLB"},
{name:"Verile",surname:"Aplin",email:"vaplin1f@apple.com",password:"WVHZM8J06ciG"},
{name:"Morissa",surname:"Benduhn",email:"mbenduhn1g@nymag.com",password:"EuGf6i"},
{name:"Angelica",surname:"Timpany",email:"atimpany1h@ning.com",password:"nIhFuie5pc5d"},
{name:"Kessiah",surname:"Traves",email:"ktraves1i@joomla.org",password:"ABvVX0SGUum"},
{name:"James",surname:"Wearn",email:"jwearn1j@google.cn",password:"rhgXNl9Hx"},
{name:"Ham",surname:"Bentke",email:"hbentke1k@examiner.com",password:"4dMuexN6L4"},
{name:"Kirsti",surname:"Pittel",email:"kpittel1l@desdev.cn",password:"FKNUJFvfvb"},
{name:"Addison",surname:"Franey",email:"afraney1m@scribd.com",password:"3OOxOOQm"},
{name:"Alanson",surname:"Hukin",email:"ahukin1n@sogou.com",password:"JJEyOc"},
{name:"Jermaine",surname:"Ochterlonie",email:"jochterlonie1o@51.la",password:"zha44bBe"},
{name:"Frederique",surname:"Noore",email:"fnoore1p@printfriendly.com",password:"HdvfpTUD"},
{name:"Colman",surname:"Harly",email:"charly1q@vinaora.com",password:"962AKslob"},
{name:"Nerita",surname:"Vinecombe",email:"nvinecombe1r@godaddy.com",password:"RDuNWH4EYW"},
{name:"Dori",surname:"Izzatt",email:"dizzatt1s@nationalgeographic.com",password:"VQBQxnOq"},
{name:"Nanine",surname:"Guidotti",email:"nguidotti1t@ucla.edu",password:"Gvf5bJuH5tL"},
{name:"Sebastien",surname:"Tacker",email:"stacker1u@fema.gov",password:"GaevaNzSz7x"},
{name:"Felicio",surname:"Fairpo",email:"ffairpo1v@noaa.gov",password:"3PNNfN5qbd"},
{name:"Harp",surname:"Antonovic",email:"hantonovic1w@soundcloud.com",password:"O44KBsy5W"},
{name:"Grange",surname:"Showering",email:"gshowering1x@biblegateway.com",password:"feY5XE5"},
{name:"Diannne",surname:"Hourihan",email:"dhourihan1y@umn.edu",password:"E2nD7N"},
{name:"Egbert",surname:"Arnall",email:"earnall1z@facebook.com",password:"ZDpQkV9t7"},
{name:"Agneta",surname:"McCaskill",email:"amccaskill20@tinyurl.com",password:"XK6FVAql"},
{name:"Kendre",surname:"Safont",email:"ksafont21@indiatimes.com",password:"UKJtxO"},
{name:"Yvor",surname:"Pottell",email:"ypottell22@bravesites.com",password:"axVe0Puw1Eb"},
{name:"Gale",surname:"Baldini",email:"gbaldini23@theglobeandmail.com",password:"39kRwoE0"},
{name:"Dennis",surname:"Riply",email:"driply24@google.com.br",password:"fEMivGN3"},
{name:"Janessa",surname:"Cornford",email:"jcornford25@i2i.jp",password:"HztDV5uj2Y"},
{name:"Griz",surname:"St. Aubyn",email:"gstaubyn26@liveinternet.ru",password:"OmlrygCWuM"},
{name:"Anton",surname:"Darling",email:"adarling27@tripadvisor.com",password:"bC6qxgrv"},
{name:"Mil",surname:"Kingdon",email:"mkingdon28@a8.net",password:"YHi6Hdk"},
{name:"Raimundo",surname:"Warret",email:"rwarret29@loc.gov",password:"DXbIBh"},
{name:"Agustin",surname:"Taw",email:"ataw2a@ox.ac.uk",password:"9nqNRu"},
{name:"Charlie",surname:"Hadingham",email:"chadingham2b@instagram.com",password:"hDepNEpZi8x"},
{name:"Fancy",surname:"Philott",email:"fphilott2c@slate.com",password:"AG7ipsc8RL"},
{name:"Shaun",surname:"Asals",email:"sasals2d@smugmug.com",password:"orgMTLeZy"},
{name:"Myra",surname:"Kornacki",email:"mkornacki2e@geocities.com",password:"KbrB5HcK"},
{name:"Andria",surname:"Althrop",email:"aalthrop2f@ucoz.ru",password:"UGajw8VKT"},
{name:"Alberto",surname:"MacDonald",email:"amacdonald2g@hostgator.com",password:"Zi44QIb"},
{name:"Billye",surname:"Cockings",email:"bcockings2h@engadget.com",password:"Vp98m2sf38"},
{name:"Goldi",surname:"Venner",email:"gvenner2i@deliciousdays.com",password:"ocSNmXpazo"},
{name:"Jolyn",surname:"Hair",email:"jhair2j@plala.or.jp",password:"IxWERyY3U"},
{name:"Kanya",surname:"Ketton",email:"kketton2k@multiply.com",password:"AcYCGpHHQ"},
{name:"Anderea",surname:"Lohmeyer",email:"alohmeyer2l@google.ru",password:"2lUTLC8sTs"},
{name:"Emanuele",surname:"Belly",email:"ebelly2m@google.fr",password:"lygh93"},
{name:"Tatum",surname:"Lowdiane",email:"tlowdiane2n@storify.com",password:"Vcv4lQT4EL"},
{name:"Alvy",surname:"Wayland",email:"awayland2o@goodreads.com",password:"BCgKZwR"},
{name:"Abbie",surname:"Fearenside",email:"afearenside2p@china.com.cn",password:"GehkZG"},
{name:"Wyn",surname:"Burroughes",email:"wburroughes2q@trellian.com",password:"OzmKiWzdWC"},
{name:"Sydelle",surname:"Flott",email:"sflott2r@prweb.com",password:"fHOcmRaAQq5s"},
{name:"Etta",surname:"Consterdine",email:"econsterdine2s@youku.com",password:"1TGXEr"},
{name:"Corilla",surname:"Ruby",email:"cruby2t@t-online.de",password:"XoEBh1ULc8"},
{name:"Tallulah",surname:"Attwell",email:"tattwell2u@howstuffworks.com",password:"nEvp9W7530P"},
{name:"Courtnay",surname:"Headland",email:"cheadland2v@who.int",password:"ErHWlRn5Jguf"},
{name:"Blanca",surname:"Kinsell",email:"bkinsell2w@stanford.edu",password:"dtD2boy1"},
{name:"Claude",surname:"Grumley",email:"cgrumley2x@noaa.gov",password:"07GMzE71"},
{name:"Donni",surname:"Skelding",email:"dskelding2y@nymag.com",password:"46iAo8yIm5gf"},
{name:"Allsun",surname:"Fosserd",email:"afosserd2z@blogspot.com",password:"FfOLrm"},
{name:"Evanne",surname:"Corbould",email:"ecorbould30@surveymonkey.com",password:"mG3RFAetGSaG"},
{name:"Armand",surname:"Tourville",email:"atourville31@hugedomains.com",password:"39Vhuxdp3"},
{name:"Katina",surname:"Botler",email:"kbotler32@google.co.jp",password:"AXOTSfqx"},
{name:"Cole",surname:"Threlfall",email:"cthrelfall33@youtube.com",password:"W5VvS4"},
{name:"Harlie",surname:"Knock",email:"hknock34@phpbb.com",password:"dp3rFDBNvOR"},
{name:"Ashli",surname:"Gomar",email:"agomar35@ask.com",password:"snZDS7rj"},
{name:"Che",surname:"Bachman",email:"cbachman36@uiuc.edu",password:"utfzWP"},
{name:"Eirena",surname:"Tousy",email:"etousy37@wix.com",password:"BfVcLqrr"},
{name:"Friedrick",surname:"Klaaassen",email:"fklaaassen38@wired.com",password:"NXp9dq4"},
{name:"Leonanie",surname:"Jeves",email:"ljeves39@wunderground.com",password:"LDNSTBOJR"},
{name:"Sherwynd",surname:"MacCollom",email:"smaccollom3a@opera.com",password:"ElpmPW7giP"},
{name:"Othilia",surname:"Le Houx",email:"olehoux3b@seesaa.net",password:"s98AeFT7"},
{name:"Cal",surname:"Kanter",email:"ckanter3c@dell.com",password:"w0D8f74"},
{name:"Cynthea",surname:"Infantino",email:"cinfantino3d@sitemeter.com",password:"NfWkMhhiXQTZ"},
{name:"Cherianne",surname:"Cleal",email:"ccleal3e@japanpost.jp",password:"myXfnfaD24B"},
{name:"Miguela",surname:"Hearnes",email:"mhearnes3f@webs.com",password:"2X1NGKf1ff"},
{name:"Corissa",surname:"Battleson",email:"cbattleson3g@reddit.com",password:"sGPVJ3BR29"},
{name:"Ulla",surname:"Calan",email:"ucalan3h@apple.com",password:"4pOilAMeZ"},
{name:"Gerry",surname:"Rembaud",email:"grembaud3i@bbc.co.uk",password:"b9NysadzUfI"},
{name:"Zach",surname:"Kuzma",email:"zkuzma3j@ibm.com",password:"4R9tznZq8s"},
{name:"Issy",surname:"Lawley",email:"ilawley3k@sciencedirect.com",password:"kv0XJ9Ct"},
{name:"Sherri",surname:"Tinghill",email:"stinghill3l@jiathis.com",password:"On2AngyIuab"},
{name:"Alon",surname:"Noquet",email:"anoquet3m@opensource.org",password:"DZooHH5"},
{name:"Bancroft",surname:"Ducaen",email:"bducaen3n@disqus.com",password:"pEBWLf9"},
{name:"Garret",surname:"Mursell",email:"gmursell3o@geocities.com",password:"RTNwGzyY"},
{name:"Jourdan",surname:"Semered",email:"jsemered3p@cnn.com",password:"8FgByetke1Z"},
{name:"Dotti",surname:"Walduck",email:"dwalduck3q@prlog.org",password:"bilrTaUb"},
{name:"Helyn",surname:"Ackland",email:"hackland3r@surveymonkey.com",password:"dlWihKpNJ"},
{name:"Dallas",surname:"Asals",email:"dasals3s@google.cn",password:"R9BiHA"},
{name:"Blair",surname:"O'Neill",email:"boneill3t@berkeley.edu",password:"DmP1x9n1naV3"},
{name:"Gale",surname:"Hyndson",email:"ghyndson3u@posterous.com",password:"hAeEgxpJfS"},
{name:"Sholom",surname:"Wiburn",email:"swiburn3v@fc2.com",password:"hu7B9xjLJOPj"},
{name:"Kaye",surname:"Pretsel",email:"kpretsel3w@hibu.com",password:"HPUPJAaVkCK"},
{name:"Ronnie",surname:"Algy",email:"ralgy3x@google.com.br",password:"VJGHexMa"},
{name:"Fanechka",surname:"Mabley",email:"fmabley3y@sciencedaily.com",password:"bZj6bHFPkxS"},
{name:"Humphrey",surname:"Sheeres",email:"hsheeres3z@creativecommons.org",password:"168UvTY5"},
{name:"Janie",surname:"Goneau",email:"jgoneau40@t-online.de",password:"UjagpzV"},
{name:"Reggie",surname:"Comello",email:"rcomello41@joomla.org",password:"IdVix63Yk"},
{name:"Virgie",surname:"Pilkinton",email:"vpilkinton42@drupal.org",password:"MHDRB2o"},
{name:"Nickie",surname:"Critcher",email:"ncritcher43@de.vu",password:"s02eS7tSIO1"},
{name:"Laurice",surname:"Beeck",email:"lbeeck44@nih.gov",password:"tuoDwOM"},
{name:"Barton",surname:"Westmorland",email:"bwestmorland45@columbia.edu",password:"NmpoMfsl2"},
{name:"Perrine",surname:"Duerden",email:"pduerden46@google.com.au",password:"pxGLwuLuT7"},
{name:"Con",surname:"Hasel",email:"chasel47@so-net.ne.jp",password:"zCtstt"},
{name:"Meade",surname:"Esmonde",email:"mesmonde48@wordpress.org",password:"cNSexKY5Inw"},
{name:"Perl",surname:"Swadlin",email:"pswadlin49@fda.gov",password:"SKlE03fO"},
{name:"Fran",surname:"Farlamb",email:"ffarlamb4a@gizmodo.com",password:"irMOTusB9T"},
{name:"Dennie",surname:"Howkins",email:"dhowkins4b@tiny.cc",password:"YbFNmKAXkV"},
{name:"Munroe",surname:"Chicchetto",email:"mchicchetto4c@yolasite.com",password:"HGR9jmLrk"},
{name:"Krispin",surname:"Uttridge",email:"kuttridge4d@studiopress.com",password:"nmMSsJbcz"},
{name:"Rycca",surname:"Smickle",email:"rsmickle4e@comsenz.com",password:"ZrNlj5"},
{name:"Leon",surname:"Barr",email:"lbarr4f@tripadvisor.com",password:"Hfzs6Zllm"},
{name:"Amii",surname:"Yurchishin",email:"ayurchishin4g@twitpic.com",password:"i0EIghWc8tIE"},
{name:"Dianemarie",surname:"Kruszelnicki",email:"dkruszelnicki4h@fotki.com",password:"NXyOw0udJ8d"},
{name:"Reinald",surname:"Corry",email:"rcorry4i@meetup.com",password:"zanibFxZU50r"},
{name:"Rickey",surname:"Ornelas",email:"rornelas4j@umn.edu",password:"e7uhXLoj"},
{name:"Valentina",surname:"L'oiseau",email:"vloiseau4k@google.it",password:"5hrAkosipP"},
{name:"Ardelis",surname:"Lafrentz",email:"alafrentz4l@disqus.com",password:"cd7IQh8qgE"},
{name:"Rollins",surname:"Taylor",email:"rtaylor4m@patch.com",password:"8NahNg"},
{name:"Arlyne",surname:"O'Loghlen",email:"aologhlen4n@google.nl",password:"mMJk20fTY"},
{name:"Halsey",surname:"Myott",email:"hmyott4o@google.ru",password:"UrA2yRvV"},
{name:"Rinaldo",surname:"Yerborn",email:"ryerborn4p@bloglovin.com",password:"LEVvXWB0q3"},
{name:"Legra",surname:"Simonetto",email:"lsimonetto4q@nyu.edu",password:"I2odjR"},
{name:"Chickie",surname:"Walenta",email:"cwalenta4r@blinklist.com",password:"gGrGiBJK8"},
{name:"Connie",surname:"Farans",email:"cfarans4s@ning.com",password:"XOWy5T"},
{name:"Kriste",surname:"Geal",email:"kgeal4t@skype.com",password:"ikoCN1"},
{name:"Gino",surname:"Grigorio",email:"ggrigorio4u@geocities.jp",password:"F5MYiL"},
{name:"Jordain",surname:"Hedon",email:"jhedon4v@mlb.com",password:"y3xHnPR"},
{name:"Modesty",surname:"Jerratsch",email:"mjerratsch4w@cdbaby.com",password:"tmjBYw7PL"},
{name:"Tommy",surname:"Hursthouse",email:"thursthouse4x@about.com",password:"TWXgi2mf1ki"},
{name:"Clary",surname:"Breadmore",email:"cbreadmore4y@posterous.com",password:"rTKpNkg"},
{name:"Benjie",surname:"Sarton",email:"bsarton4z@noaa.gov",password:"CMsG5D0XBJ"},
{name:"Mead",surname:"Quail",email:"mquail50@trellian.com",password:"vTcL1kkqQtb"},
{name:"Ingrid",surname:"Sherreard",email:"isherreard51@de.vu",password:"8nbXll8bRJos"},
{name:"Cherice",surname:"Ead",email:"cead52@elegantthemes.com",password:"XLWbeSkz30d"},
{name:"Helga",surname:"Scruton",email:"hscruton53@xing.com",password:"D8x6q6"},
{name:"Salvidor",surname:"Huggill",email:"shuggill54@princeton.edu",password:"uU7kvb"},
{name:"Benita",surname:"Fabry",email:"bfabry55@elegantthemes.com",password:"bLUyXcK"},
{name:"Giles",surname:"Kelly",email:"gkelly56@cdc.gov",password:"mGyoKhpG"},
{name:"Guinevere",surname:"Attwooll",email:"gattwooll57@devhub.com",password:"57eE110Go7"},
{name:"Dinnie",surname:"Thaxton",email:"dthaxton58@arizona.edu",password:"xJqncOEV60"},
{name:"Boigie",surname:"Judron",email:"bjudron59@theatlantic.com",password:"AGs9bTTB"},
{name:"Ruggiero",surname:"Thorby",email:"rthorby5a@washington.edu",password:"eFPXlnnrL"},
{name:"Moritz",surname:"Daysh",email:"mdaysh5b@cargocollective.com",password:"KHyyYEzEHdRb"},
{name:"Hi",surname:"Heaysman",email:"hheaysman5c@hibu.com",password:"ohamRZ"},
{name:"Henryetta",surname:"Rykert",email:"hrykert5d@yellowbook.com",password:"rPWjP3"},
{name:"Griselda",surname:"Wernham",email:"gwernham5e@cnet.com",password:"MM7eZJ9JkZ"},
{name:"Malvina",surname:"Mulcock",email:"mmulcock5f@statcounter.com",password:"ZtneFRo"},
{name:"Milt",surname:"Elsie",email:"melsie5g@home.pl",password:"zeDJuHOkO7Fc"},
{name:"Giraud",surname:"Pettican",email:"gpettican5h@ihg.com",password:"oCNSIccb8E"},
{name:"Fabian",surname:"Broome",email:"fbroome5i@nymag.com",password:"UxXnDVDgED"},
{name:"Cacilie",surname:"Amsden",email:"camsden5j@cocolog-nifty.com",password:"PSfgQvTRy8UA"}
]

const userOrganization = [
	{name:"Timoteo",surname:"Bussens",email:"tbussens0@census.gov",password:"o1Wcmy3b5",organizationId:1},
{name:"Shanie",surname:"Wagner",email:"swagner1@wordpress.com",password:"sg4Ib2Jp",organizationId:2},
{name:"Madelene",surname:"Snel",email:"msnel2@princeton.edu",password:"yRws8Z1hoy",organizationId:3},
{name:"Glenna",surname:"Losemann",email:"glosemann3@bloglovin.com",password:"BSbtR67vB4",organizationId:4},
{name:"Darin",surname:"Krink",email:"dkrink4@meetup.com",password:"OreJahKPGyE6",organizationId:5},
{name:"Ced",surname:"Asling",email:"casling5@upenn.edu",password:"b7tIU4z4oYee",organizationId:6},
{name:"Gloriane",surname:"Whelan",email:"gwhelan6@economist.com",password:"xYI5arQmn",organizationId:7},
{name:"Abelard",surname:"Linacre",email:"alinacre7@uiuc.edu",password:"ofnat1pO",organizationId:8},
{name:"Traver",surname:"Bourne",email:"tbourne8@oakley.com",password:"vmGvq4Cg3",organizationId:9},
{name:"Hyacinthia",surname:"Neesham",email:"hneesham9@nymag.com",password:"EdpCqD",organizationId:10}
]

const {Event, Date, Organization, EventLocation,Ticket, User, Location, Category, EventCategory, City, UserRole} = sequelize.models

export async function MockData(){

    Promise.all([Organization.bulkCreate(organization), City.bulkCreate(cities), Category.bulkCreate(categories)])
    .then(async result => {

		await Location.bulkCreate(locations)
		events = events.map((event: any) => {
			return { ...event, background_image: images[Math.floor(Math.random() * (images.length - 1) + 1)]}
		})
    	let eventcreated = await Event.bulkCreate(events)
		await EventLocation.bulkCreate(eventLocations)
		await Date.bulkCreate(dates)

		let userscreated = await User.bulkCreate(users)

		for (let i = 0; i < userscreated.length; i++) {
			await UserRole.create({userId: userscreated[i].getDataValue("id"), roleId: 1010})
		}

		let userOrganizationcreated = await User.bulkCreate(userOrganization)

		for (let i = 0; i < userOrganizationcreated.length; i++) {
			await UserRole.create({userId: userOrganizationcreated[i].getDataValue("id"), roleId: 1010})
			await UserRole.create({userId: userOrganizationcreated[i].getDataValue("id"), roleId: 2020})
		}
			
		for (let i = 0; i < eventcreated.length; i++) {
			await EventCategory.create({eventId: eventcreated[i].getDataValue("id"), categoryId: Math.floor(Math.random() * (6 - 1) + 1)})
		}

    })
}